import { latexSymbol } from "./interfaces";


export const arrowSymbols: latexSymbol[] = [

        { display: '←', latex: '\\leftarrow', tooltip: '\\leftarrow' },
        { display: '⟵', latex: '\\longleftarrow', tooltip: '\\longleftarrow' },
        { display: '↑', latex: '\\uparrow', tooltip: '\\uparrow' },
        { display: '⇐', latex: '\\Leftarrow', tooltip: '\\Leftarrow' },
        { display: '⟸', latex: '\\Longleftarrow', tooltip: '\\Longleftarrow' },
        { display: '⇑', latex: '\\Uparrow', tooltip: '\\Uparrow' },
        { display: '→', latex: '\\rightarrow', tooltip: '\\rightarrow' },
        { display: '⟶', latex: '\\longrightarrow', tooltip: '\\longrightarrow' },
        { display: '↓', latex: '\\downarrow', tooltip: '\\downarrow' },

        { display: '⇒', latex: '\\Rightarrow', tooltip: '\\Rightarrow' },
        { display: '⟹', latex: '\\Longrightarrow', tooltip: '\\Longrightarrow' },
        { display: '⇓', latex: '\\Downarrow', tooltip: '\\Downarrow' },
        { display: '↔', latex: '\\leftrightarrow', tooltip: '\\leftrightarrow' },
        { display: '⟷', latex: '\\longleftrightarrow', tooltip: '\\longleftrightarrow' },
        { display: '↕', latex: '\\updownarrow', tooltip: '\\updownarrow' },
        { display: '⇔', latex: '\\Leftrightarrow', tooltip: '\\Leftrightarrow' },
        { display: '⟺', latex: '\\Longleftrightarrow', tooltip: '\\Longleftrightarrow' },
        { display: '⇕', latex: '\\Updownarrow', tooltip: '\\Updownarrow' },

        { display: '↦', latex: '\\mapsto', tooltip: '\\mapsto' },
        { display: '⟼', latex: '\\longmapsto', tooltip: '\\longmapsto' },
        { display: '↗', latex: '\\nearrow', tooltip: '\\nearrow' },
        { display: '↩', latex: '\\hookleftarrow', tooltip: '\\hookleftarrow' },
        { display: '↪', latex: '\\hookrightarrow', tooltip: '\\hookrightarrow' },
        { display: '↘', latex: '\\searrow', tooltip: '\\searrow' },
        { display: '↼', latex: '\\leftharpoonup', tooltip: '\\leftharpoonup' },
        { display: '⇀', latex: '\\rightharpoonup', tooltip: '\\rightharpoonup' },
        { display: '↙', latex: '\\swarrow', tooltip: '\\swarrow' },

        { display: '↽', latex: '\\leftharpoondown', tooltip: '\\leftharpoondown' },
        { display: '⇁', latex: '\\rightharpoondown', tooltip: '\\rightharpoondown' },
        { display: '↖', latex: '\\nwarrow', tooltip: '\\nwarrow' },
        { display: '⇌', latex: '\\rightleftharpoons', tooltip: '\\rightleftharpoons' },
        { display: '⟿', latex: '\\leadsto', tooltip: '\\leadsto' },
        { display: '⇢', latex: '\\dashrightarrow', tooltip: '\\dashrightarrow' },
        { display: '⇠', latex: '\\dashleftarrow', tooltip: '\\dashleftarrow' },
        { display: '⇆', latex: '\\leftleftarrows', tooltip: '\\leftleftarrows' },
        { display: '⇉', latex: '\\leftrightrightarrows', tooltip: '\\leftrightrightarrows' },

        { display: '⇚', latex: '\\Lleftarrow', tooltip: '\\Lleftarrow' },
        { display: '↞', latex: '\\twoheadleftarrow', tooltip: '\\twoheadleftarrow' },
        { display: '↢', latex: '\\leftarrowtail', tooltip: '\\leftarrowtail' },
        { display: '↫', latex: '\\looparrowleft', tooltip: '\\looparrowleft' },
        { display: '⇋', latex: '\\leftrightharpoons', tooltip: '\\leftrightharpoons' },
        { display: '↶', latex: '\\curvearrowleft', tooltip: '\\curvearrowleft' },
        { display: '⥀', latex: '\\circlearrowleft', tooltip: '\\circlearrowleft' },
        { display: '↰', latex: '\\Lsh', tooltip: '\\Lsh' },

        { display: '⇈', latex: '\\upuparrows', tooltip: '\\upuparrows' },
        { display: '↿', latex: '\\upharpoonleft', tooltip: '\\upharpoonleft' },
        { display: '↧', latex: '\\downharpoonleft', tooltip: '\\downharpoonleft' },
        { display: '⊸', latex: '\\multimap', tooltip: '\\multimap' },
        { display: '⇝', latex: '\\leftrightsquigarrow', tooltip: '\\leftrightsquigarrow' },
        { display: '⇉', latex: '\\rightrightarrows', tooltip: '\\rightrightarrows' },
        { display: '⇄', latex: '\\rightleftarrows', tooltip: '\\rightleftarrows' },
        { display: '⇛', latex: '\\rightrightarrows', tooltip: '\\rightrightarrows' },
        { display: '⇌', latex: '\\rightleftarrows', tooltip: '\\rightleftarrows' },

        { display: '↠', latex: '\\twoheadrightarrow', tooltip: '\\twoheadrightarrow' },
        { display: '↣', latex: '\\rightarrowtail', tooltip: '\\rightarrowtail' },
        { display: '↬', latex: '\\looparrowright', tooltip: '\\looparrowright' },
        { display: '⇊', latex: '\\rightleftharpoons', tooltip: '\\rightleftharpoons' },
        { display: '↷', latex: '\\curvearrowright', tooltip: '\\curvearrowright' },
        { display: '⥁', latex: '\\circlearrowright', tooltip: '\\circlearrowright' },
        { display: '⇊', latex: '\\downdownarrows', tooltip: '\\downdownarrows' },
        { display: '↾', latex: '\\upharpoonright', tooltip: '\\upharpoonright' },
        { display: '⇝', latex: '\\rightsquigarrow', tooltip: '\\rightsquigarrow' },

        { display: '↚', latex: '\\nleftarrow', tooltip: '\\nleftarrow' },
        { display: '↛', latex: '\\nrightarrow', tooltip: '\\nrightarrow' },
        { display: '⇍', latex: '\\nLeftarrow', tooltip: '\\nLeftarrow' },
        { display: '⇏', latex: '\\nRightarrow', tooltip: '\\nRightarrow' },
        { display: '↮', latex: '\\nleftrightarrow', tooltip: '\\nleftrightarrow' },
        { display: '⇎', latex: '\\nLeftrightarrow', tooltip: '\\nLeftrightarrow' },

];
