import { latexSymbol } from "./interfaces";

export const miscellaneousSymbolsTwo: latexSymbol[] = [

        { display: '*', latex: '\\ast', tooltip: '\\ast' },
        { display: '±', latex: '\\pm', tooltip: '\\pm' },
        { display: '∩', latex: '\\cap', tooltip: '\\cap' },
        { display: '◁', latex: '\\lhd', tooltip: '\\lhd' },
        { display: '⋆', latex: '\\star', tooltip: '\\star' },
        { display: '∓', latex: '\\mp', tooltip: '\\mp' },
        { display: '∪', latex: '\\cup', tooltip: '\\cup' },
        { display: '▷', latex: '\\rhd', tooltip: '\\rhd' },
        { display: '·', latex: '\\cdot', tooltip: '\\cdot' },
        { display: '⨿', latex: '\\amalg', tooltip: '\\amalg' },

        { display: '⊎', latex: '\\uplus', tooltip: '\\uplus' },
        { display: '◃', latex: '\\triangleleft', tooltip: '\\triangleleft' },
        { display: '○', latex: '\\circ', tooltip: '\\circ' },
        { display: '⊙', latex: '\\odot', tooltip: '\\odot' },
        { display: '⊔', latex: '\\sqcup', tooltip: '\\sqcup' },
        { display: '▹', latex: '\\triangleright', tooltip: '\\triangleright' },
        { display: '●', latex: '\\bullet', tooltip: '\\bullet' },
        { display: '⊖', latex: '\\ominus', tooltip: '\\ominus' },
        { display: '∨', latex: '\\vee', tooltip: '\\vee' },
        { display: '⊴', latex: '\\unlhd', tooltip: '\\unlhd' },

        { display: '◯', latex: '\\bigcirc', tooltip: '\\bigcirc' },
        { display: '⊕', latex: '\\oplus', tooltip: '\\oplus' },
        { display: '∧', latex: '\\wedge', tooltip: '\\wedge' },
        { display: '⊵', latex: '\\unrhd', tooltip: '\\unrhd' },
        { display: '◇', latex: '\\diamond', tooltip: '\\diamond' },
        { display: '⊘', latex: '\\oslash', tooltip: '\\oslash' },
        { display: '†', latex: '\\dagger', tooltip: '\\dagger' },
        { display: '▽', latex: '\\bigtriangledown', tooltip: '\\bigtriangledown' },
        { display: '×', latex: '\\times', tooltip: '\\times' },
        { display: '⊗', latex: '\\otimes', tooltip: '\\otimes' },

        { display: '‡', latex: '\\ddagger', tooltip: '\\ddagger' },
        { display: '△', latex: '\\bigtriangleup', tooltip: '\\bigtriangleup' },
        { display: '÷', latex: '\\div', tooltip: '\\div' },
        { display: '≀', latex: '\\wr', tooltip: '\\wr' },
        { display: '\\', latex: '\\setminus', tooltip: '\\setminus' },
        { display: '⊥', latex: '\\bot', tooltip: '\\bot' },
        { display: '·', latex: '\\centerdot', tooltip: '\\centerdot' },
        { display: '□', latex: '\\Box', tooltip: '\\Box' },
        { display: '∨', latex: '\\veebar', tooltip: '\\veebar' },
        { display: '⊤', latex: '\\top', tooltip: '\\top' },

        { display: '⊛', latex: '\\circledast', tooltip: '\\circledast' },
        { display: '⊞', latex: '\\boxplus', tooltip: '\\boxplus' },
        { display: '⋎', latex: '\\curlyvee', tooltip: '\\curlyvee' },
        { display: '⋉', latex: '\\rightthreetimes', tooltip: '\\rightthreetimes' },
        { display: '⊚', latex: '\\circledcirc', tooltip: '\\circledcirc' },
        { display: '⊟', latex: '\\boxminus', tooltip: '\\boxminus' },
        { display: '⋏', latex: '\\curlywedge', tooltip: '\\curlywedge' },
        { display: '⋊', latex: '\\leftthreetimes', tooltip: '\\leftthreetimes' },
        { display: '⊖', latex: '\\circleddash', tooltip: '\\circleddash' },
        { display: '⊠', latex: '\\boxtimes', tooltip: '\\boxtimes' },

        { display: '⋒', latex: '\\Cap', tooltip: '\\Cap' },
        { display: '⋓', latex: '\\Cup', tooltip: '\\Cup' },
        { display: '⊕', latex: '\\dotplus', tooltip: '\\dotplus' },
        { display: '⊡', latex: '\\boxdot', tooltip: '\\boxdot' },
        { display: '∫', latex: '\\intercal', tooltip: '\\intercal' },
        { display: '∗', latex: '\\divideontimes', tooltip: '\\divideontimes' },
        { display: '▪', latex: '\\square', tooltip: '\\square' },
        { display: '⩞', latex: '\\doublebarwedge', tooltip: '\\doublebarwedge' },

];