import { latexSymbol } from "./interfaces";

export const negatedRelations: latexSymbol[] = [

        { display: '≢', latex: '\\ncong', tooltip: '\\ncong' },
        { display: '≰', latex: '\\nleq', tooltip: '\\nleq' },
        { display: '≱', latex: '\\ngeq', tooltip: '\\ngeq' },
        { display: '⊈', latex: '\\nsubseteqq', tooltip: '\\nsubseteqq' },
        { display: '∤', latex: '\\nmid', tooltip: '\\nmid' },
        { display: '≰', latex: '\\nleqq', tooltip: '\\nleqq' },
        { display: '≱', latex: '\\ngeqq', tooltip: '\\ngeqq' },
        { display: '⊉', latex: '\\nsupseteqq', tooltip: '\\nsupseteqq' },
        { display: '∦', latex: '\\nparallel', tooltip: '\\nparallel' },
        { display: '⪇', latex: '\\nleqslant', tooltip: '\\nleqslant' },

        { display: '⪈', latex: '\\ngeqslant', tooltip: '\\ngeqslant' },
        { display: '⊈', latex: '\\nsubseteq', tooltip: '\\nsubseteq' },
        { display: '∦', latex: '\\nshortmid', tooltip: '\\nshortmid' },
        { display: '≮', latex: '\\nless', tooltip: '\\nless' },
        { display: '≯', latex: '\\ngtr', tooltip: '\\ngtr' },
        { display: '⊉', latex: '\\nsupseteq', tooltip: '\\nsupseteq' },
        { display: '∦', latex: '\\nshortparallel', tooltip: '\\nshortparallel' },
        { display: '⊀', latex: '\\nprec', tooltip: '\\nprec' },
        { display: '⊁', latex: '\\nsucc', tooltip: '\\nsucc' },
        { display: '⊂', latex: '\\subsetneq', tooltip: '\\subsetneq' },

        { display: '≁', latex: '\\nsim', tooltip: '\\nsim' },
        { display: '⪷', latex: '\\npreceq', tooltip: '\\npreceq' },
        { display: '⪸', latex: '\\nsucceq', tooltip: '\\nsucceq' },
        { display: '⊃', latex: '\\supsetneq', tooltip: '\\supsetneq' },
        { display: '⫋', latex: '\\nVDash', tooltip: '\\nVDash' },
        { display: '⪹', latex: '\\precnapprox', tooltip: '\\precnapprox' },
        { display: '⪺', latex: '\\succnapprox', tooltip: '\\succnapprox' },
        { display: '⊊', latex: '\\subsetneqq', tooltip: '\\subsetneqq' },
        { display: '⫋', latex: '\\nvDash', tooltip: '\\nvDash' },
        { display: '⪻', latex: '\\precnsim', tooltip: '\\precnsim' },

        { display: '⪼', latex: '\\succnsim', tooltip: '\\succnsim' },
        { display: '⊋', latex: '\\supsetneqq', tooltip: '\\supsetneqq' },
        { display: '⫋', latex: '\\nvdash', tooltip: '\\nvdash' },
        { display: '⋦', latex: '\\lnapprox', tooltip: '\\lnapprox' },
        { display: '⋧', latex: '\\gnapprox', tooltip: '\\gnapprox' },
        { display: '⫋', latex: '\\varsubsetneq', tooltip: '\\varsubsetneq' },
        { display: '⋪', latex: '\\ntriangleleft', tooltip: '\\ntriangleleft' },
        { display: '≨', latex: '\\lneq', tooltip: '\\lneq' },
        { display: '≩', latex: '\\gneq', tooltip: '\\gneq' },
        { display: '⫋', latex: '\\varsupsetneq', tooltip: '\\varsupsetneq' },

        { display: '⋬', latex: '\\ntrianglelefteq', tooltip: '\\ntrianglelefteq' },
        { display: '≨', latex: '\\lneqq', tooltip: '\\lneqq' },
        { display: '≩', latex: '\\gneqq', tooltip: '\\gneqq' },
        { display: '⫋', latex: '\\varsubsetneqq', tooltip: '\\varsubsetneqq' },
        { display: '⋦', latex: '\\lnsim', tooltip: '\\lnsim' },
        { display: '⋧', latex: '\\gnsim', tooltip: '\\gnsim' },
        { display: '⫋', latex: '\\varsupsetneqq', tooltip: '\\varsupsetneqq' },
        { display: '⋭', latex: '\\ntrianglerighteq', tooltip: '\\ntrianglerighteq' },
        { display: '≨', latex: '\\lvertneqq', tooltip: '\\lvertneqq' },
        { display: '≩', latex: '\\gvertneqq', tooltip: '\\gvertneqq' },

];