import { latexSymbol } from "./interfaces";

export const relationsSymbols: latexSymbol[] = [

        { display: '≡', latex: '\\equiv', tooltip: '\\equiv' },
        { display: '≤', latex: '\\leq', tooltip: '\\leq' },
        { display: '≥', latex: '\\geq', tooltip: '\\geq' },
        { display: '⊥', latex: '\\perp', tooltip: '\\perp' },
        { display: '≅', latex: '\\cong', tooltip: '\\cong' },
        { display: '≺', latex: '\\prec', tooltip: '\\prec' },
        { display: '≻', latex: '\\succ', tooltip: '\\succ' },
        { display: '∣', latex: '\\mid', tooltip: '\\mid' },

        { display: '≠', latex: '\\neq', tooltip: '\\neq' },
        { display: '⪯', latex: '\\preceq', tooltip: '\\preceq' },
        { display: '⪰', latex: '\\succeq', tooltip: '\\succeq' },
        { display: '∥', latex: '\\parallel', tooltip: '\\parallel' },
        { display: '∼', latex: '\\sim', tooltip: '\\sim' },
        { display: '≪', latex: '\\ll', tooltip: '\\ll' },
        { display: '≫', latex: '\\gg', tooltip: '\\gg' },
        { display: '⋈', latex: '\\bowtie', tooltip: '\\bowtie' },

        { display: '≃', latex: '\\simeq', tooltip: '\\simeq' },
        { display: '⊂', latex: '\\subset', tooltip: '\\subset' },
        { display: '⊃', latex: '\\supset', tooltip: '\\supset' },
        { display: '⋉', latex: '\\Join', tooltip: '\\Join' },
        { display: '≈', latex: '\\approx', tooltip: '\\approx' },
        { display: '⊆', latex: '\\subseteq', tooltip: '\\subseteq' },
        { display: '⊇', latex: '\\supseteq', tooltip: '\\supseteq' },
        { display: '⋉', latex: '\\ltimes', tooltip: '\\ltimes' },

        { display: '≍', latex: '\\asymp', tooltip: '\\asymp' },
        { display: '⊏', latex: '\\sqsubset', tooltip: '\\sqsubset' },
        { display: '⊐', latex: '\\sqsupset', tooltip: '\\sqsupset' },
        { display: '⋊', latex: '\\rtimes', tooltip: '\\rtimes' },
        { display: '≐', latex: '\\doteq', tooltip: '\\doteq' },
        { display: '⊑', latex: '\\sqsubseteq', tooltip: '\\sqsubseteq' },
        { display: '⊒', latex: '\\sqsupseteq', tooltip: '\\sqsupseteq' },
        { display: '⌣', latex: '\\smile', tooltip: '\\smile' },

        { display: '∝', latex: '\\propto', tooltip: '\\propto' },
        { display: '⊣', latex: '\\dashv', tooltip: '\\dashv' },
        { display: '⊢', latex: '\\vdash', tooltip: '\\vdash' },
        { display: '⌢', latex: '\\frown', tooltip: '\\frown' },
        { display: '⊨', latex: '\\models', tooltip: '\\models' },
        { display: '∈', latex: '\\in', tooltip: '\\in' },
        { display: '∋', latex: '\\ni', tooltip: '\\ni' },
        { display: '∉', latex: '\\notin', tooltip: '\\notin' },

        { display: '≲', latex: '\\lesssim', tooltip: '\\lesssim' },
        { display: '≤', latex: '\\leqq', tooltip: '\\leqq' },
        { display: '≥', latex: '\\geqq', tooltip: '\\geqq' },
        { display: '⋚', latex: '\\lessgtr', tooltip: '\\lessgtr' },
        { display: '∼', latex: '\\thicksim', tooltip: '\\thicksim' },
        { display: '⪅', latex: '\\leqslant', tooltip: '\\leqslant' },
        { display: '⪆', latex: '\\geqslant', tooltip: '\\geqslant' },
        { display: '⋛', latex: '\\lesseqgtr', tooltip: '\\lesseqgtr' },
        { display: '≃', latex: '\\backsimeq', tooltip: '\\backsimeq' },
        { display: '⪉', latex: '\\lessapprox', tooltip: '\\lessapprox' },

        { display: '⪊', latex: '\\gtrapprox', tooltip: '\\gtrapprox' },
        { display: '⋜', latex: '\\lesseqqgtr', tooltip: '\\lesseqqgtr' },
        { display: '≍', latex: '\\backsim', tooltip: '\\backsim' },
        { display: '⋘', latex: '\\lll', tooltip: '\\lll' },
        { display: '⋙', latex: '\\ggg', tooltip: '\\ggg' },
        { display: '⋛', latex: '\\gtreqqless', tooltip: '\\gtreqqless' },
        { display: '≦', latex: '\\triangleq', tooltip: '\\triangleq' },
        { display: '⪅', latex: '\\lessdot', tooltip: '\\lessdot' },
        { display: '⪆', latex: '\\gtrdot', tooltip: '\\gtrdot' },
        { display: '≷', latex: '\\gtrless', tooltip: '\\gtrless' },

        { display: '≅', latex: '\\circeq', tooltip: '\\circeq' },
        { display: '⋦', latex: '\\lesssim', tooltip: '\\lesssim' },
        { display: '⋧', latex: '\\gtrsim', tooltip: '\\gtrsim' },
        { display: '∍', latex: '\\backepsilon', tooltip: '\\backepsilon' },
        { display: '≏', latex: '\\bumpeq', tooltip: '\\bumpeq' },
        { display: '⋦', latex: '\\eqslantless', tooltip: '\\eqslantless' },
        { display: '⋧', latex: '\\eqslantgtr', tooltip: '\\eqslantgtr' },
        { display: '≎', latex: '\\Bumpeq', tooltip: '\\Bumpeq' },
        { display: '⋞', latex: '\\precsim', tooltip: '\\precsim' },

        { display: '⋟', latex: '\\succsim', tooltip: '\\succsim' },
        { display: '≐', latex: '\\doteqdot', tooltip: '\\doteqdot' },
        { display: '⋞', latex: '\\precapprox', tooltip: '\\precapprox' },
        { display: '⋟', latex: '\\succapprox', tooltip: '\\succapprox' },
        { display: '∣', latex: '\\shortmid', tooltip: '\\shortmid' },
        { display: '≈', latex: '\\thickapprox', tooltip: '\\thickapprox' },
        { display: '⊂', latex: '\\Subset', tooltip: '\\Subset' },
        { display: '⊃', latex: '\\Supset', tooltip: '\\Supset' },
        { display: '⌣', latex: '\\smallfrown', tooltip: '\\smallfrown' },

        { display: '≒', latex: '\\fallingdotseq', tooltip: '\\fallingdotseq' },
        { display: '⊆', latex: '\\subseteqq', tooltip: '\\subseteqq' },
        { display: '⊇', latex: '\\supseteqq', tooltip: '\\supseteqq' },
        { display: '⌢', latex: '\\smallsmile', tooltip: '\\smallsmile' },
        { display: '≓', latex: '\\risingdotseq', tooltip: '\\risingdotseq' },
        { display: '⫅', latex: '\\sqsubset', tooltip: '\\sqsubset' },
        { display: '⫆', latex: '\\sqsupset', tooltip: '\\sqsupset' },
        { display: '⊢', latex: '\\Vdash', tooltip: '\\Vdash' },
        { display: '∝', latex: '\\varpropto', tooltip: '\\varpropto' },
        { display: '⋞', latex: '\\preccurlyeq', tooltip: '\\preccurlyeq' },

        { display: '⋟', latex: '\\succcurlyeq', tooltip: '\\succcurlyeq' },
        { display: '⊣', latex: '\\vDash', tooltip: '\\vDash' },
        { display: '∴', latex: '\\therefore', tooltip: '\\therefore' },
        { display: '⋎', latex: '\\curlyeqprec', tooltip: '\\curlyeqprec' },
        { display: '⋏', latex: '\\curlyeqsucc', tooltip: '\\curlyeqsucc' },
        { display: '⊨', latex: '\\Vvdash', tooltip: '\\Vvdash' },
        { display: '∵', latex: '\\because', tooltip: '\\because' },
        { display: '◀', latex: '\\blacktriangleleft', tooltip: '\\blacktriangleleft' },
        { display: '▶', latex: '\\blacktriangleright', tooltip: '\\blacktriangleright' },
        { display: '∥', latex: '\\shortparallel', tooltip: '\\shortparallel' },

        { display: '≢', latex: '\\eqcirc', tooltip: '\\eqcirc' },
        { display: '◁', latex: '\\trianglelefteq', tooltip: '\\trianglelefteq' },
        { display: '▷', latex: '\\trianglerighteq', tooltip: '\\trianglerighteq' },
        { display: '∦', latex: '\\nshortparallel', tooltip: '\\nshortparallel' },
        { display: '≠', latex: '\\neq', tooltip: '\\neq' },
        { display: '▽', latex: '\\vartriangleleft', tooltip: '\\vartriangleleft' },
        { display: '△', latex: '\\vartriangleright', tooltip: '\\vartriangleright' },

];


